[env]
ELM_HOME = "/tmp/wrap_review_0.5.0/elm_home"
WRAP_HOME = "/tmp/wrap_review_0.5.0/wrap_home"
WRAP_FEATURE_CACHE = 1
_.path = ['{{config_root}}/node_modules/.bin']

[alias]
elm = "wrap"

[tools]
elm = "0.19"
node = "24"
just = "1"

"npm:elm-format" = "0.8"
"npm:elm-review" = "2"
"npm:run-pty" = "5.0.0"
"npm:elm-esm" = "1.1.4"